# backend:
#   name: github
#   repo: Nallasivan30/decapPublic  # Format: username/repo
#   branch: main                    # Your default branch
#   site_domain: https://regal-gumdrop-45c902.netlify.app  # No trailing slash!

backend:
  name: git-gateway
  repo: Nallasivan30/decapPublic
  branch: main


media_folder: "content/images"    # Where media files are saved
public_folder: "/content/images"  # Public path for media

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", default: ["blog"]}

  - name: "images"
    label: "Image Gallery"
    folder: "content/images"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["hero", "gallery", "thumbnail"]}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "Site Configuration"
        name: "site"
        file: "content/settings/site.json"
        fields:
          - {label: "Site Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Hero Image", name: "hero_image", widget: "image"}

  - name: "testimonials"
    label: "Testimonials"
    folder: "content/testimonials"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - {label: "Customer Name", name: "name", widget: "string"}
      - {label: "Role / Subtitle", name: "role", widget: "string", required: false}
      - {label: "Review Text", name: "review", widget: "text"}
      - {label: "Star Rating", name: "rating", widget: "number", value_type: "int", min: 1, max: 5, default: 5}
      - {label: "Profile Image", name: "image", widget: "image", required: false}
